bboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

main/urls.py
from django.urls import path
from . import views
from .views import BBLoginView, profile

app_name = 'main'


urlpatterns = [
    path('accounts/login/', BBLoginView.as_view(), name='login'),

    path('accounts/profile/', profile, name='profile'),
    path('<str:page>', views.other_page, name='other'),
    path('', views.index, name='index')
]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class AdvUser(AbstractUser):
    its_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошёл активацию?')
    send_messages = models.BooleanField(default=True, verbose_name = 'Слать оповещение о новых комментариях?')
class Meta(AbstractUser.Meta):
    pass

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.template.exceptions import TemplateDoesNotExist
from django.template.loader import get_template

def index(request):
    return render(request, 'main/index.html')

def other_page(request, page):
    try:
        template  = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        return Http404
    return HttpResponse(template.render(request=request))

class BBLoginView(LoginView):
        template_name = 'main/login.html'

@login_required
def profile(request):
    return render(request, 'main/profile.html')

main/templates/layout/basic.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Главная{% endblock %}
        – Доска объявлений</title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css"
        href="{% static 'main/style.css' %}">
        {% bootstrap_javascript %}
    </head>
    
    <body class="container-fluid">
        <header class="mb-4">
            <h1 class="display-1 text-center">Объявления</h1>
        </header>
        <nav class="row navbar navbar-expand-md bg-light">
            <div class="col container">
                <a class="navbar-brand" href="{% url 'main:index' %}">Главная</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                            data-bs-toggle="dropdown" href="#">Профиль</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
                                <a class="dropdown-item" href="#">Изменить личные данные</a>
                                <a class="dropdown-item" href="#">Изменить пароль</a>
                                <hr class="dropdown-divider">
                                <form class="px-3">
                                    {% csrf_token %}
                                    {% bootstrap_button 'Выйти'
                                    button_class='btn-danger' %}
                                </form>
                                <hr class="dropdown-divider">
                                <a class="dropdown-item" href="#">Удалить</a>
                            </div>
                        </div>
                        {%else%}
                            <a class="nav-link" href="#">Регистрация</a>
                            <a class="nav-link" href="{% url 'main:login' %}">Вход</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        <div class="row">
            <nav class="col-md-auto nav flex-column bg-light">
                <span class="nav-link root">Недвижимость</span>
                <a class="nav-link" href="#">Жильё</a>
                <a class="nav-link" href="#">Склады</a>
                <a class="nav-link" href="#">Гаражи</a>
                <span class="nav-link root" href="#">Транспорт</span>
                <a class="nav-link" href="#">Легковой</a>
                <a class="nav-link" href="#">Грузовой</a>
                <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
            </nav>
            <main class="col py-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
            </main>
        </div>
        <footer class="mt-3">
            <p class="text-end fst-italic">&copy; читатели.</p>
        </footer>
    </body>
</html>

main/templates/main/about.html
{% extends 'layout/basic.html' %}

{% block title %}О сайте{% endblock %}

{% block content %}
    <h1>About us</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi voluptatum labore deleniti tenetur eius. Sapiente harum eius, repudiandae error temporibus explicabo necessitatibus distinctio cum mollitia, omnis et ipsam veritatis saepe.
    Cumque culpa veniam maiores ipsa sapiente placeat sequi cum ad, aperiam quo eaque aliquid sint hic illum quaerat ratione dolorum, voluptatibus ipsum recusandae ea vitae voluptate? Magni suscipit placeat veritatis.
    Saepe, voluptate! Asperiores rerum tempora, dolor quas eius nobis quidem. Inventore aliquam commodi cupiditate, laudantium beatae magni ab distinctio ut tempora repellendus veritatis numquam provident quibusdam dolorum, debitis omnis? Quis?
    Inventore corporis commodi cupiditate, nesciunt dicta molestias iste ipsa nam sapiente fugiat eveniet nobis eius nulla voluptas, officia autem? Consequatur, unde iusto architecto quis dolores placeat illum explicabo facilis corrupti.
    Iste, ipsum accusantium ipsam aliquam perspiciatis reprehenderit quas quos corrupti nesciunt mollitia, natus, labore deserunt ut temporibus? Amet pariatur mollitia quo at aspernatur. Optio ullam ducimus deserunt voluptate pariatur provident?</p>
{% endblock %}

main/templates/main/index.html
{% extends 'layout/basic.html' %}

{% block content %}
    <h2>Последние 10 объявлений</h2>
{% endblock %}

main/templates/main/login.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Вход{% endblock %}
{% block content %}
    <h2>Вход</h2>
    {% if user.is_authenticated %}
        <p>Вы уже выполнили вход.</p>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
            <input type="hidden" name="next" value="{{ next }}">
            {% bootstrap_button 'Войти' %}
        </form>
    {% endif %}
{% endblock %}

main/templates/main/profile.html
{% extends 'layout/basic.html' %}
{% block title %}Профиль пользователя!{% endblock %}
{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
        <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %}
        <p>Здравствуйте!</p>
    {% endif %}
        <h3>Ваши объявления</h3>
{% endblock %}